ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :create, :destroy, :show, :edit, :new, :update] do
    resources :cat_rental_requests, only: [:index]
  end 

  resources :cat_rental_requests, only: [:index, :new, :create]


end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord

  validates :birth_date, :color, :name, :sex, presence: true


  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: 'CatRentalRequest',
    dependent: :destroy 
end

ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validate :does_not_overlap_approved_request


  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: 'Cat'


  def overlapping_requests
    CatRentalRequest
      .where("(cat_rental_requests.cat_id = #{cat_id})
      AND NOT (cat_rental_requests.end_date < '#{start_date}'
      OR cat_rental_requests.start_date > '#{end_date}')")
  end

  def overlapping_approved_requests
    overlapping_requests
      .where("cat_rental_requests.status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests
      .where("cat_rental_requests.status = 'PENDING'")
  end

  def approve!
    conflicting_requests = overlapping_pending_requests
    ApplicationRecord.transaction do
      self.update(status: 'APPROVED')
      conflicting_requests.each do |request|
        request.update(status: 'DENIED')
      end
    end
    self
  end

  def deny!
    self.update(status: 'DENIED')
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      self.errors[:start_date] << 'Dates overlap with approved request'
    end
  end
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @cat_rental_requests = CatRentalRequest.all
    render :index
  end


  def new
    @cat_rental_request = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)

    if @cat_rental_request.save
      redirect_to cat_rental_requests_url(@cat_rental_request)
    else
      @cat_rental_request = CatRentalRequest.new
      @cats = Cat.all
      render :new
    end
  end

  private

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end


end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    @cat_rental_requests = []

    @cat.cat_rental_requests.each do |request|
      @cat_rental_requests << [request.id, request.start_date, request.end_date, request.status]
    end
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cat_rental_requests/index.html.erb
<h1>All cat rental requests!</h1>

<ul>
  <% @cat_rental_requests.each do |cat_rental_request| %>
    <li><%= cat_rental_request.cat_id  %></li>
    <li><%= cat_rental_request.start_date  %></li>
    <li><%= cat_rental_request.end_date %></li>
  <% end %>
</ul>

ninety_nine_cats/app/views/cat_rental_requests/new.html.erb
<h1>Add a request for rental!</h1>

<form action=  '<%= cat_rental_requests_url %>' method="post">

  <br>

  <label for="Id">Cat Id</label>
  <select name="cat_rental_request[cat_id]">
    <option disabled selected>--Please Select a Cat--</option>
    <% @cats.each do |cat| %>
      <% name = cat.name %>
      <% id = cat.id %>
      <option value= <%= id %>  ><%= name %></option>
    <% end %>
  </select>

  <br>

  <label for="start_date">Start Date</label>
  <input id="start_date" type="date" name="cat_rental_request[start_date]" >

  <label for="end_date">End Date</label>
  <input id="end_date" type="date" name="cat_rental_request[end_date]" >

  <br>

  <input type="submit" value= "Add a request">
</form>

ninety_nine_cats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action=  '<%= action_url %>' method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>

  <label for="M">M</label>
  <input id="M" type="radio" name="cat[sex]" value = "M" <%= cat.sex == 'M' ? 'checked' : '' %>>
  <label for="F">F</label>
  <input id="F" type="radio" name="cat[sex]" value = "F" <%= cat.sex == 'F' ? 'checked' : '' %>>

  <br>

  <label for="color">Color</label>
  <select name="cat[color]">
    <option disabled>--Please Select Color--</option>
    <option value="White" <%= cat.color == 'White' ? 'selected' : '' %>>White</option>
    <option value="Brown" <%= cat.color == 'Brown' ? 'selected' : '' %>>Brown</option>
    <option value="Black" <%= cat.color == 'Black' ? 'selected' : '' %>>Black</option>
    <option value="Purple" <%= cat.color == 'Purple' ? 'selected' : '' %>>Purple</option>
    <option value="Yellow" <%= cat.color == 'Yellow' ? 'selected' : '' %>>Yellow</option>
    <option value="Orange" <%= cat.color == 'Orange' ? 'selected' : '' %>>Orange</option>
  </select>

  <br>

  <label for="birth_date">Birth Day</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>

  <label for="description">Description</label>
  <textarea name="cat[description]">
    <%= cat.description %>
  </textarea>

  <br>

  <input type="submit" value= "<%= action == :edit ? 'Edit cat' : 'Add Cat'%>"> 
</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<h1>Edit Cat!</h1>

<%= render "form", action: :edit, cat: @cat %>

ninety_nine_cats/app/views/cats/index.html.erb
<h1>All cat!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><%= cat.name  %></li>
  <% end %>
</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<h1>Add Cat!</h1>

<%= render "form", action: :new, cat: @cat %>

ninety_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<h3>BirthDate: <%= @cat.birth_date %> </h3>
<h3>Color: <%= @cat.color %> </h3>
<h3>Sex: <%= @cat.sex %> </h3>
<h3>Rental Requests: <%= @cat_rental_requests %> </h3>
<p> <%= @cat.description %> </p>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- #<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>